### PR TITLE
New logs adaptor which supports writing to multiple files

### PR DESCRIPTION
**Pull request by quxiao**
Add an new beego logs adaptor, which supports writing different files according to different log level in configuration.

Configuration example:

        {  
            "levelfiles": [{
                "levelnames": ["debug", "trace"],
                "filename": "some.log.debug"
            },{
                "levelnames": ["info"],
                "filename": "some.log"
            },{
                "levelnames": ["warning", "critical"],
                "filename": "some.log.wf"
            }]
        }

### CODE REVIEW

**Comment by astaxie** [comment]
@JessonChan what's your opinion?

**Comment by JessonChan** [comment]
this pr is almost like #1721 but i think it's a little verbose and has some same code compared to `file.go`,such as multiFileLogWriter struct and fileLogWriter.
and this pr is not complete, i can not find  where is the definition of the function "logLevelName2Int".

**Comment by quxiao** [comment]
@JessonChan sorry, I forgot to commit one new file, and the function logLevelName2Int is in it.

**Comment by astaxie** [comment]
I think dup with #1721

**Pull request closed without merging**
