### PR TITLE
Fix cookies in accordance with the "net / http" and Flash usage

### PR DESCRIPTION
**Pull request by mlgd**
Fixed issue of Flash cookies that are deleted before being read
Max-age parameter conform to "net/http" Cookie

### CODE REVIEW

**Comment by mlgd** [comment]
Please rebuild on Travis because it's crash on "go get github.com/couchbase/go-couchbase"

**Comment by ysqi** [comment]
hi @mlgd  ,  `for range` work on go v1.4+ .  Detail discuss see #1623.  You need fix your code and commit again.

**Comment by sheng** [comment]
Hi @mlgd,

Sorry, I read your code, but did not understand what it means.😳
And I want to let you know that my fix worked for me properly. **I mean the Flash feature worked properly.**

But I also have a small oversight.😋
I just fixed it.

Please see my pull #1703.

**Comment by mlgd** [comment]
@sheng : ok your last commit https://github.com/sheng/beego/commit/4bd656f79f7e56e96851db27d8861304e7434d12 is the same that mine

@ysql : my code don't need a fix. It's Beego continuous integration with Travis CI who need that. See https://github.com/astaxie/beego/issues/1715 & https://travis-ci.org/astaxie/beego/builds/110949040

**Pull request merged**
