### PR TITLE
filter support &

### PR DESCRIPTION
**Pull request by HarryWang29**

### CODE REVIEW

**Comment by flycash** [comment]
pkg/orm is in develop-2.0. We won't merge any feature to branch develop.

**Comment by HarryWang29** [comment]
> Thanks for your PR. But now we are refactoring ORM module, the orm has been moved to pkg/orm.
> And could you explain why you need this feature?

其实就是 #3994 的延续吧，之前提交了update操作的位运算，现在想起来吧where里也加一下

**Comment by flycash** [comment]
我竟然没看懂 " & ?=?"，所已生成的语句类似于 "where a & xxx = yyyy"，是么？

**Comment by HarryWang29** [comment]
恩恩，是啊，where nums & 0xA = 0x8这样吧，来确定int类型的二进制位的1/0

**Comment by flycash** [comment]
可以的。不过可惜我们暂时不会接受任何合并到develop分支的请求。因为我们已经在develop2.0上搞了。这个develop分支只用于修复一下紧急的，会导致程序崩溃的BUG。

**Pull request closed without merging**
