### PR TITLE
V1.11.0

### PR DESCRIPTION
**Pull request by astaxie**

### CODE REVIEW

**Comment by astaxie** [comment]
@DennisMao Could you add the release notes here?

**Comment by mapreal19** [comment]
@DennisMao are there any release notes? Also did you guys considered Trunk Based Development: https://trunkbaseddevelopment.com/ ? I think it'll be easier to maintain instead of both master/develop

**Comment by DennisMao** [comment]
@mapreal19  Thanks for your advice.We will discuss it.

**Comment by DennisMao** [comment]
Fix data race #3390 
Fix panic on NewOrmWithDB() #3388 
Support dynamically add task #3387 
Add transport setting example #3386 
Fix arbitrary file read #3383 
Add custom fs template #3382
ORM: support filter raw sql #3378 
Bump Go versions and use 1.n.x to get latest minor versions #3371 
Add prefix to sessionId #3352 
Fix '/' can use dynamic directory #3345 
Fix numRow #3344 
Add Go 1.11 version #3340 
Support redis URI format #3339 
Add link to time ranking #3335 
ORM: replace panic() with error() on field filtering. #3333 
Route: support annotated filter #3319 
Add lock to session module #3317 
Supports go module #3313 
Admin: support output with format #3295 
config/ini: Fix read over 4096 length values #3292 
route: remove panic on Redirect() #3289 
context: Add access to http.Pusher #3280 
ORM: revert sending ErrNoRows #3278 
Task: fix bug of tasks that only some but not all are executed #3275 
breaks dependency on TestNewBeeMap Testcase #3274

**Pull request merged**
