### PR TITLE
Develop 2.0

### PR DESCRIPTION
**Pull request by flycash**

### CODE REVIEW

**Comment by flycash** [comment]
Hi @gdhameeja, we had change the directory so you need to rebase this branch. 
Feel free to tell me if you have any problems.

**Comment by gdhameeja** [comment]
@flycash I think `ftr/multi-server` also needs to be rebased with `develop-2.0`

**Comment by flycash** [comment]
This PR merge develop-2.0 into ftr/multi-server. It should be fine. And you just need to rebase ftr/multi-server

**Comment by gdhameeja** [comment]
@flycash Done

**Pull request merged**
