### PR TITLE
Fix joins for reverse(many) with custom pk

### PR DESCRIPTION
**Pull request by pjoe**
Fix issue for reverse many relations with inner join being made on id column even if model specifies custom pk name.

Also includes test covering this.

### CODE REVIEW

**Comment by astaxie** [comment]
LGTM

**Comment by astaxie** [comment]
@pjoe I have tested this merged in my local Mac. it looks it break the testing.

```
--- FAIL: TestInsertTestData (0.00s)
	orm_test.go:164:
		Error: datatype mismatch
		orm_test.go:691:
		      682:
		      683:       for _, group := range groups {
		      684:           id, err := dORM.Insert(group)
		      685:           throwFail(t, err)
		      686:           throwFail(t, AssertIs(id > 0, true))
		      687:
		      688:           num := len(group.Permissions)
		      689:           if num > 0 {
		      690:               nums, err := dORM.QueryM2M(group, "permissions").Add(group.Permissions)
		 >>   691:               throwFailNow(t, err)
```

**Comment by pjoe** [comment]
@astaxie weird, here is my output:
```
$ ORM_DRIVER=sqlite3 ORM_SOURCE=:memory: go test -v github.com/astaxie/beego/orm
=== RUN   TestGetDB
--- PASS: TestGetDB (0.00s)
=== RUN   TestSyncDb
--- PASS: TestSyncDb (0.00s)
=== RUN   TestRegisterModels
--- PASS: TestRegisterModels (0.00s)
=== RUN   TestModelSyntax
--- PASS: TestModelSyntax (0.00s)
=== RUN   TestDataTypes
--- PASS: TestDataTypes (0.00s)
=== RUN   TestNullDataTypes
--- PASS: TestNullDataTypes (0.00s)
=== RUN   TestDataCustomTypes
--- PASS: TestDataCustomTypes (0.00s)
=== RUN   TestCRUD
--- PASS: TestCRUD (0.00s)
=== RUN   TestInsertTestData
--- PASS: TestInsertTestData (0.00s)
=== RUN   TestCustomField
--- PASS: TestCustomField (0.00s)
=== RUN   TestExpr
--- PASS: TestExpr (0.00s)
=== RUN   TestOperators
--- PASS: TestOperators (0.00s)
=== RUN   TestSetCond
--- PASS: TestSetCond (0.00s)
=== RUN   TestLimit
--- PASS: TestLimit (0.00s)
=== RUN   TestOffset
--- PASS: TestOffset (0.00s)
=== RUN   TestOrderBy
--- PASS: TestOrderBy (0.00s)
=== RUN   TestAll
--- PASS: TestAll (0.00s)
=== RUN   TestOne
--- PASS: TestOne (0.00s)
=== RUN   TestValues
--- PASS: TestValues (0.00s)
=== RUN   TestValuesList
--- PASS: TestValuesList (0.00s)
=== RUN   TestValuesFlat
--- PASS: TestValuesFlat (0.00s)
=== RUN   TestRelatedSel
--- PASS: TestRelatedSel (0.00s)
=== RUN   TestReverseQuery
--- PASS: TestReverseQuery (0.00s)
=== RUN   TestLoadRelated
--- PASS: TestLoadRelated (0.00s)
=== RUN   TestQueryM2M
--- PASS: TestQueryM2M (0.00s)
=== RUN   TestQueryRelate
--- PASS: TestQueryRelate (0.00s)
=== RUN   TestPkManyRelated
--- PASS: TestPkManyRelated (0.00s)
=== RUN   TestPrepareInsert
--- PASS: TestPrepareInsert (0.00s)
=== RUN   TestRawExec
--- PASS: TestRawExec (0.00s)
=== RUN   TestRawQueryRow
--- PASS: TestRawQueryRow (0.00s)
=== RUN   TestQueryRows
--- PASS: TestQueryRows (0.00s)
=== RUN   TestRawValues
--- PASS: TestRawValues (0.00s)
=== RUN   TestRawPrepare
--- PASS: TestRawPrepare (0.00s)
=== RUN   TestUpdate
--- PASS: TestUpdate (0.00s)
=== RUN   TestDelete
--- PASS: TestDelete (0.00s)
=== RUN   TestTransaction
--- PASS: TestTransaction (0.00s)
=== RUN   TestReadOrCreate
--- PASS: TestReadOrCreate (0.00s)
PASS
ok  	github.com/astaxie/beego/orm	0.022s
```

I'm am however not running of latest dev, but some earlier version. Lemme know if there is anything I can do to help, you can find me on slack in working hours (Europe TZ)

**Comment by astaxie** [comment]
@pjoe yea, maybe in your branch works well. maybe this https://github.com/astaxie/beego/pull/1451 cause the problem. I am still test in the latest develop branch

**Comment by astaxie** [comment]
@pjoe I found the issue. it caused by #1451. I fixed it https://github.com/astaxie/beego/commit/4375ca84d153a185c5162cc27e03666593aceb53

**Comment by astaxie** [comment]
@pjoe But I also found the problem in this PR.

you use GID string as the pk. but orm not alowed now. 

then you throwFail(t, AssertIs(id > 0, true)). So when I testing in mysql. it broken

**Comment by pjoe** [comment]
I tried running test from latest develop with mysql, but getting failures during syncdb :(
```
src/github.com/astaxie/beego/orm (develop)$ git log -n 1 --format=oneline
4375ca84d153a185c5162cc27e03666593aceb53 fix the sqlite m2m
src/github.com/astaxie/beego/orm (develop)$ docker run -d -e MYSQL_ROOT_PASSWORD=foo -e MYSQL_DATABASE=test -p 3306 --name beego-mysql mysql
src/github.com/astaxie/beego/orm (develop)$ ORM_DRIVER=mysql ORM_SOURCE="root:foo@tcp(localhost:$(docker inspect --format='{{(index (index .NetworkSetti
ngs.Ports "3306/tcp") 0).HostPort}}' beego-mysql))/test" go test -v
=== RUN   TestGetDB
--- PASS: TestGetDB (0.00s)
=== RUN   TestSyncDb
--- FAIL: TestSyncDb (0.00s)
        orm_test.go:149: 
                Error: Error 1101: BLOB, TEXT, GEOMETRY or JSON column 'text' can't have a default value
                orm_test.go:192: 
                      183:       RegisterModel(new(Tag))
                      184:       RegisterModel(new(Comment))
                      185:       RegisterModel(new(UserBig))
                      186:       RegisterModel(new(PostTags))
                      187:       RegisterModel(new(Group))
                      188:       RegisterModel(new(Permission))
                      189:       RegisterModel(new(GroupPermissions))
                      190:   
                      191:       err := RunSyncdb("default", true, false)
                 >>   192:       throwFail(t, err)
```

Investigating further ...

**Comment by pjoe** [comment]
Figured out this happens when running with latest mysql (5.7) .. with 5.5 I get:
```
src/github.com/astaxie/beego/orm (develop)$ docker run -d -e MYSQL_ROOT_PASSWORD=foo -e MYSQL_DATABASE=test -p 3306 --name beego-mysql mysql:5.5
src/github.com/astaxie/beego/orm (develop)$ ORM_DRIVER=mysql ORM_SOURCE="root:foo@tcp(localhost:$(docker inspect --format='{{(index (index .NetworkSettings.Ports "3306/tcp") 0).HostPort}}' beego-mysql))/test?charset=utf8" go test -v
...
=== RUN   TestInsertTestData
--- FAIL: TestInsertTestData (0.06s)
        orm_test.go:149: 
                Error: expected: `true`, get `false`
                orm_test.go:686: 
                      677:       for _, permission := range permissions {
                      678:           id, err := dORM.Insert(permission)
                      679:           throwFail(t, err)
                      680:           throwFail(t, AssertIs(id > 0, true))
                      681:       }
                      682:   
                      683:       for _, group := range groups {
                      684:           id, err := dORM.Insert(group)
                      685:           throwFail(t, err)
                 >>   686:           throwFail(t, AssertIs(id > 0, true))

        orm_test.go:149: 
                Error: expected: `true`, get `false`
                orm_test.go:686: 
                      677:       for _, permission := range permissions {
                      678:           id, err := dORM.Insert(permission)
                      679:           throwFail(t, err)
                      680:           throwFail(t, AssertIs(id > 0, true))
                      681:       }
                      682:   
                      683:       for _, group := range groups {
                      684:           id, err := dORM.Insert(group)
                      685:           throwFail(t, err)
                 >>   686:           throwFail(t, AssertIs(id > 0, true))

...
```

**Comment by pjoe** [comment]
I think the check on returned id should just be removed as it doesn't make sense in this case, as there is no auto inc column for group. So change like this should be fine:
```diff
diff --git a/orm/orm_test.go b/orm/orm_test.go
index eb87242..14509b5 100644
--- a/orm/orm_test.go
+++ b/orm/orm_test.go
@@ -681,9 +681,8 @@ The program—and web server—godoc processes Go source files to extract docume
        }
 
        for _, group := range groups {
-               id, err := dORM.Insert(group)
+               _, err := dORM.Insert(group)
                throwFail(t, err)
-               throwFail(t, AssertIs(id > 0, true))
 
                num := len(group.Permissions)
                if num > 0 {
```

**Comment by astaxie** [comment]
@pjoe I already fix this problem in https://github.com/astaxie/beego/commit/7dbeb2c39a7889fc8dd7e06583e3982852945785

**Comment by pjoe** [comment]
This looks to work for me with mysql 5.5, I'm still seeing other issues on 5.7, added comment to https://github.com/astaxie/beego/issues/1563

**Pull request merged**
