### PR TITLE
save raw request body to input.Context.Request.Body

### PR DESCRIPTION
**Pull request by zuoRambo**
I meet the following scenario that: IOS client misused the compression algorithm and the declared `Content-Type` was **gzip**, but the body of the request actually needed to be decompressed with `zlib`, and these clients could not be upgraded for many reasons.

image

This MergeRequest mainly saves the raw information of the request body, so that it can be used in custom filters. The developer can use the new decompression algorithm to parse the request body based on the body's signature information.

### CODE REVIEW

**Comment by zuoRambo** [comment]
```
package filters

import (
	"compress/zlib"
	"io"
	"io/ioutil"
	
	"git.xxx/internal/log"
	
	"github.com/astaxie/beego"
	"github.com/astaxie/beego/context"
	"github.com/astaxie/beego/utils"
)

// @link https://developer.mozilla.org/zh-CN/docs/Web/HTTP/Headers/Content-Encoding
var RequestCompressedType = []string{
	"gzip", "compress", "deflate", "identiy", "br",
}

func DetectCompress() func(ctx *context.Context) {
	return func(ctx *context.Context) {
		if ctx.Request.Body == nil {
			log.AppLogger.Warn(ctx.Request.Context(), "request body is nil and can't be handle again")
			return
		}
		// 请求头声明启用了压缩，但是压缩使用的算法和声明不一致，需要再次根据body进行解压
		if utils.InSlice(ctx.Input.Header("Content-Type"), RequestCompressedType) {
			if len(ctx.Input.RequestBody) == 0 {
				reader, err := zlib.NewReader(&io.LimitedReader{R: ctx.Request.Body, N: beego.BConfig.MaxMemory})
				if err != nil {
					log.AppLogger.Warn(ctx.Request.Context(), "use zlib deflate failed. err: %v", err)
					return
				}
				requestBody, _ := ioutil.ReadAll(reader)
				ctx.Request.Body.Close()
				ctx.Input.RequestBody = requestBody
			}
		}
	}
}

```

**Comment by zuoRambo** [comment]
@astaxie 谢大可以抽空看下么

**Comment by zuoRambo** [comment]
@JessonChan @slene @miraclesu @fuxiaohei @ysqi

**Comment by zuoRambo** [comment]
?

**Comment by zuoRambo** [comment]
每日一看

**Comment by zuoRambo** [comment]
hello. can you hear me?

**Comment by zuoRambo** [comment]
Help！anybody here ?

**Comment by hantmac** [comment]
😭

**Pull request closed without merging**
