### PR TITLE
add comment router path configuration

### PR DESCRIPTION
**Pull request by AllenX2018**
Add an option to config the comment router directory to solve the probelm with comment router generation when using go module. See the discussion in #4093

### CODE REVIEW

**Comment by AllenX2018** [comment]
> Does it works for sub directory? For example, if my controller directory looks like:

I'm sorry that it won't work for sub directory. I will add new commits in this pr to support it.

> And if we use go.mod, but it's out of GOPATH, does it work?

It works when we use go.mod. I've tested in my environment.

**Comment by AllenX2018** [comment]
I add some commits:

- I introduce the `golang.org/x/tools/go/packages` package which can be used to scan all of the packages and build the AST of a directory. With this package, we don't need to call `parserPkg` every time when we call `Include` to add comment router, so I add a new function called `registerCommentRouter` to hook list and `parserPkg` will be called in it only once(develop mode)

- Since `parserPkg` will be called only once now, the `getpathTime` should scan the comment router directory recursively to find the last update time

- I've tested for both go.mod and GOPATH scenario

**Comment by AllenX2018** [comment]
@flycash

**Comment by flycash** [comment]
Thank you! I will test this PR next days. It will take some times, please wait for my feedback!

**Comment by flycash** [comment]
Could you move these changes to the pkg since we copied all files to that directory? We want to adapt to the new project layout which all APIs are under pkg directory. We will remove old files in the future

**Comment by AllenX2018** [comment]
OK, I will move them to the files under pkg directory.

**Comment by AllenX2018** [comment]
> Could you move these changes to the pkg since we copied all files to that directory?

Done

**Comment by AllenX2018** [comment]
I clone your project to my local environment and test. It failed because `pkg.Syntax` is nil too. I debug and find that the reason is that the version of the `golang.org/x/tools` package which the go.mod depend on is too old. It need to be updated. I add the below line to the go.mod file of beego and the problem will be solved:

```
golang.org/x/tools v0.0.0-20200806234136-990129eca547
```

Pls try again and tell if you have any other question!

**Comment by AllenX2018** [comment]
I've add a commit to update the verion of `golang.org/x/tools` for go.mod to depend on.

**Comment by flycash** [comment]
@AllenX2018 Thank you! It works well. And could you please merge develop-2.0? We had fixed some unit tests, CI is more stable.

**Pull request merged**
