### PR TITLE
fix #671

### LINKED ISSUE #671: ORM m2m reverse bug
Hello.
I have tried to connect a model (`Movie`) with a model (`Person`) using two `Many-To-Many` relationships (`Directors` and `Writers`).

```Go
package models

import (
	"github.com/astaxie/beego/orm"
)

type Movie struct {
	Id          int    `json:"id"`
	Title       string `json:"title" orm:"size(200)"`
	
	// Many to many relationships
	Directors  []*Person   `orm:"rel(m2m);rel_through(github.com/crackcomm/myapp/models.MovieDirector)" json:"directors,omitempty"`
	Writers    []*Person   `orm:"rel(m2m);rel_through(github.com/crackcomm/myapp/models.MovieWriter)" json:"writers,omitempty"`
}

type MovieDirector struct {
	Id     int
	Movie  *Movie  `orm:"rel(fk)"`
	Person *Person `orm:"rel(fk)"`
}

type MovieWriter struct {
	Id     int
	Movie  *Movie  `orm:"rel(fk)"`
	Person *Person `orm:"rel(fk)"`
}

type Person struct {
	Id      int    `json:"id"`
	Name    string `orm:"size(200)" json:"name,omitempty"`
	
	Directed []*Movie `orm:"reverse(many);rel_through(github.com/crackcomm/myapp/models.MovieDirector)" json:"directed,omitempty"`
	Written  []*Movie `orm:"reverse(many);rel_through(github.com/crackcomm/myapp/models.MovieWriter)" json:"written,omitempty"`
}
```

Then when I'm trying to load related objects into a `Movie` model, I've got a `nil pointer dereference` error.

First of all - ORM maps `*Movie.Directors` to `*Person.Written` (it shouldn't).
And doesn't map `*Movie.Writers` reverse (this I think causes error).

```Go
movie := &models.Movie{}

o.QueryTable("movie").Filter("title", "Pulp Fiction").One(movie)

if err != nil {
	panic(err)
}

log.Printf("Movie: %v\n", movie)

o.LoadRelated(movie, "Directors")
o.LoadRelated(movie, "Writers")
```

After some code digging I came to conclusion that `*fieldInfo.reverseFieldInfoM2M` is a `nil` and probably causes an error.

```
D:/backup/go/src/github.com/astaxie/beego/orm/orm.go 345
D:/backup/go/src/github.com/astaxie/beego/orm/orm.go 297
D:/backup/go/src/github.com/astaxie/beego/orm/orm.go 208
```

PS.
All models are registered.
Before I tried `rel_through` i also tried `rel_table`.
This error appears on master branch (develop too, just checked).

### PR DESCRIPTION
**Pull request by ADone**

### CODE REVIEW

**Comment by AyliD** [comment]
i updated manually the files on my server till they will be pulled, but im still having the same panic.
Do i need to do something after updating the files?

**Comment by AyliD** [comment]
To be more specific this is my panic:

2015/07/08 18:40:52 [router.go:879] [C] the request url is  /api/iso/display/1 
2015/07/08 18:40:52 [router.go:880] [C] Handler crashed with error runtime error: invalid memory address or nil pointer dereference 
2015/07/08 18:40:52 [router.go:886] [C] /usr/local/go/src/runtime/asm_amd64.s:401 
2015/07/08 18:40:52 [router.go:886] [C] /usr/local/go/src/runtime/panic.go:387 
2015/07/08 18:40:52 [router.go:886] [C] /usr/local/go/src/runtime/panic.go:42 
2015/07/08 18:40:52 [router.go:886] [C] /usr/local/go/src/runtime/sigpanic_unix.go:26 
2015/07/08 18:40:52 [router.go:886] [C] /usr/local/bin/go/src/github.com/astaxie/beego/orm/orm.go:385 
2015/07/08 18:40:52 [router.go:886] [C] /usr/local/bin/go/src/github.com/astaxie/beego/orm/orm.go:337 
2015/07/08 18:40:52 [router.go:886] [C] /usr/local/bin/go/src/github.com/astaxie/beego/orm/orm.go:248 
2015/07/08 18:40:52 [router.go:886] [C] /opt/go_repo_server/src/repository/models/iso/render_iso.go:88 
2015/07/08 18:40:52 [router.go:886] [C] /opt/go_repo_server/src/repository/controllers/iso_api/api.go:30 
2015/07/08 18:40:52 [router.go:886] [C] /usr/local/go/src/runtime/asm_amd64.s:401 
2015/07/08 18:40:52 [router.go:886] [C] /usr/local/go/src/reflect/value.go:419 
2015/07/08 18:40:52 [router.go:886] [C] /usr/local/go/src/reflect/value.go:296 
2015/07/08 18:40:52 [router.go:886] [C] /usr/local/bin/go/src/github.com/astaxie/beego/router.go:803 
2015/07/08 18:40:52 [router.go:886] [C] /usr/local/go/src/net/http/server.go:1703 
2015/07/08 18:40:52 [router.go:886] [C] /usr/local/go/src/net/http/server.go:1204 
2015/07/08 18:40:52 [router.go:886] [C] /usr/local/go/src/runtime/asm_amd64.s:2232


and on Line /opt/go_repo_server/src/repository/models/iso/render_iso.go:88 

im Doing additional LoadRelated to the second column which points to m2m table... (O.LoadRelated(&iso, "BuildReport"))


func DisplayById(Iso_Id int64) []byte {

	iso := Iso{Id: Iso_Id}
	O.Read(&iso)
	O.LoadRelated(&iso, "IsoMetaData")
	O.LoadRelated(&iso, "UserData")
	iso.IsoMetaData = LoadIsoMetaData(iso.IsoMetaData.Id)
	iso.IsoMetaData.OsMetaData = LoadOsMetaData(iso.IsoMetaData.OsMetaData.Id)
	O.LoadRelated(&iso, "BuildReport")
	iso.BuildReport = LoadEntities(iso.BuildReport)
	iso.UserData = LoadEntities(iso.UserData)
	data, _ := json.Marshal(iso)
	return data
}

type Iso struct {
	Id           int64        `orm:"pk;auto"`
	UserData     []*Entity    `orm:"rel(m2m);rel_table(iso__data_entities)"`
	BuildReport  []*Entity    `orm:"rel(m2m);rel_table(iso__report_entities)"`
}

type Entity struct {
	Id          int64          `orm:"pk;auto"`
	Comment     string         `orm:"size(250);null"`
	Description string         `orm:"size(1000);null"`
	EntityGroup *EntityGroup   `orm:"rel(fk)"`
	Component   *Component     `orm:"rel(fk)"`
	BaseUrls    []*BaseUrl     `orm:"rel(m2m);rel_table(entity__base_urls)"`
	Rpms        []*Rpm         `orm:"rel(m2m);rel_table(entity__rpms)"`
	IsoMetaData []*IsoMetaData `orm:"reverse(many);rel_table(iso_meta_data__entities)"`
	Reports     []*Iso         `orm:"reverse(many);rel_table(iso__report_entities)"`
	Data        []*Iso         `orm:"reverse(many);rel_table(iso__data_entities)"`
	IsMetaData  bool           `orm:"default(true)"`
}

**Comment by ADone** [comment]
@AyliD,  try to use rel_through() tag
My models below:
```
type Tag struct {
	Id                int
	Tag               string
	ApprovedCampaigns []*Campaign `orm:"reverse(many);rel_through(xml_api/models.IncludeCampaignTag)"`
	RejectedCampaigns []*Campaign `orm:"reverse(many);rel_through(xml_api/models.ExcludeCampaignTag)"`
}

func (this *Tag) TableName() string {
	return "tags"
}

type IncludeCampaignTag struct {
	Id       int
	Tag      *Tag      `orm:"rel(fk)"`
	Campaign *Campaign `orm:"rel(fk)"`
}

type ExcludeCampaignTag struct {
	Id       int
	Tag      *Tag      `orm:"rel(fk)"`
	Campaign *Campaign `orm:"rel(fk)"`
}

func (this *IncludeCampaignTag) TableName() string {
	return "include_campaigns_tags"
}

func (this *ExcludeCampaignTag) TableName() string {
	return "exclude_campaigns_tags"
}

type Campaign struct {
	Id         int
	IncludeTags []*Tag     `orm:"rel(m2m);rel_through(xml_api/models.IncludeCampaignTag)"`
	ExcludeTags []*Tag     `orm:"rel(m2m);rel_through(xml_api/models.ExcludeCampaignTag)"`
}
```

**Comment by AyliD** [comment]
Hi, im am trying to work with 'rel_through' im keeping getting error on wrong rel_through value `**` cannot find table.

No matter how i try to setup the pkg.path.ModelName

my f.s structure is:

app name is repository located under "src"
repository/models/iso/

under that directory i have many files packaged as "iso_schema"

in the package i created 2 new structs and i also have the original structs with new rel_through definition:

type UserData struct {
	Id     int64
	Iso    *Iso    `orm:"rel(fk)"`
	Entity *Entity `orm:"rel(fk)"`
}

func (self *UserData) TableName() string {
	return "user_data"
}

type BuildReport struct {
	Id     int64
	Iso    *Iso    `orm:"rel(fk)"`
	Entity *Entity `orm:"rel(fk)"`
}

func (self *BuildReport) TableName() string {
	return "build_report"
}

type Iso struct {
	Id          int64        `orm:"pk;auto"`
	IsoMetaData *IsoMetaData `orm:"rel(fk)"`
	UserData     []*Entity `orm:"rel(m2m);rel_through(repository/models/iso_schema.UserData)"`
	BuildReport  []*Entity `orm:"rel(m2m);rel_through(repository/models/iso_schema.BuildReport)"`
}

type Entity struct {
	Id          int64          `orm:"pk;auto"`
	Reports     []*Iso         `orm:"reverse(many);rel_through(repository/models/iso_schema.BuildReport)"`
	Data        []*Iso         `orm:"reverse(many);rel_through(repository/models/iso_schema.UserData)"`
}

**Comment by ADone** [comment]
@AyliD, but your join tables names are "iso__data_entities" and "iso__report_entities"
I think, you should return this names from TableName() functions of BuildReport and UserData models

**Comment by AyliD** [comment]
Thanks for the advice, im now working with rel_through and yet get the same panic.

/usr/local/go/src/runtime/asm_amd64.s:401
/usr/local/go/src/runtime/panic.go:387
/usr/local/go/src/runtime/panic.go:42
/usr/local/go/src/runtime/sigpanic_unix.go:26
/usr/local/bin/go/src/github.com/astaxie/beego/orm/orm.go:385
/usr/local/bin/go/src/github.com/astaxie/beego/orm/orm.go:337
/usr/local/bin/go/src/github.com/astaxie/beego/orm/orm.go:248
/tmp/go_repo_server/src/repository/models/iso/render_iso.go:88
/tmp/go_repo_server/src/repository/controllers/iso_api/api.go:30
/usr/local/go/src/runtime/asm_amd64.s:401
/usr/local/go/src/reflect/value.go:419
/usr/local/go/src/reflect/value.go:296
/usr/local/bin/go/src/github.com/astaxie/beego/router.go:803
/usr/local/go/src/net/http/server.go:1703
/usr/local/go/src/net/http/server.go:1204
/usr/local/go/src/runtime/asm_amd64.s:2232

**Comment by ADone** [comment]
Hmm.
```
UserData []Entity

Reports []Iso
Data []Iso
```
 try to use pointers =>
```
UserData []*Entity

Reports []*Iso
Data []*Iso
```

**Comment by AyliD** [comment]
its all with pointers...

type Iso struct {
	Id          int64        `orm:"pk;auto"`
	UserData     []*Entity `orm:"rel(m2m);rel_through(repository/models/iso.UserData)"`
	BuildReport  []*Entity `orm:"rel(m2m);rel_through(repository/models/iso.BuildReport)"`
}

type Entity struct {
	Id          int64          `orm:"pk;auto"`
	Reports     []*Iso         `orm:"reverse(many);rel_through(repository/models/iso.BuildReport)"`
	Data        []*Iso         `orm:"reverse(many);rel_through(repository/models/iso.UserData)"`
}

type UserData struct {
	Id     int64
	Iso    *Iso    `orm:"rel(fk)"`
	Entity *Entity `orm:"rel(fk)"`
}

func (self *UserData) TableName() string {
	return "iso__data_entities"
}

type BuildReport struct {
	Id     int64
	Iso    *Iso    `orm:"rel(fk)"`
	Entity *Entity `orm:"rel(fk)"`
}

func (self *BuildReport) TableName() string {
	return "iso__report_entities"
}

**Comment by ADone** [comment]
Oh, could you wrap your code with \``` symbol sequence

\`\`\`
code
\`\`\`

**Comment by AyliD** [comment]
line 88 is: 
O.LoadRelated(&iso, "BuildReport")

'''
func DisplayById(Iso_Id int64) []byte {

	iso := Iso{Id: Iso_Id}
	O.Read(&iso)
	O.LoadRelated(&iso, "IsoMetaData")
	O.LoadRelated(&iso, "UserData")
	iso.IsoMetaData = LoadIsoMetaData(iso.IsoMetaData.Id)
	iso.IsoMetaData.OsMetaData = LoadOsMetaData(iso.IsoMetaData.OsMetaData.Id)
	O.LoadRelated(&iso, "BuildReport")
	iso.BuildReport = LoadEntities(iso.BuildReport)
	iso.UserData = LoadEntities(iso.UserData)
	data, _ := json.Marshal(iso)
	return data
}
'''

**Comment by AyliD** [comment]
Thank you all is working now, i deleted orm.a file. Please update when code is beeing pulled by guthub.

**Comment by astaxie** [comment]
please send the PR to develop branch. Thanks

**Pull request closed without merging**
