### PR TITLE
Update beego.go

### PR DESCRIPTION
**Pull request by ElvizLai**
Maybe the `Hard Coding` should have a higher priority

### CODE REVIEW

**Comment by astaxie** [comment]
do you have an special example for this priority?

**Comment by ElvizLai** [comment]
I have `HttpPort = 8888` in my app.conf ,but I want to change or fix my port with 8081(for some reason that the port can not be changed through config file), so I tried using:
`beego.Run(":8081")` , but that does not work, I read the source code and found this. I not quite sure this is a good feature, but someone may need this.

**Comment by astaxie** [comment]
It's trick. sometimes we want configure has the top priority

**Comment by ElvizLai** [comment]
Absolute right, that implement is not good enough, but for now, I can not find a better way to specify the port before beego.Run().

**Pull request merged**
