### PR TITLE
policies implementation

### PR DESCRIPTION
**Pull request by OlegFX**
Hi,

Please review this implementation of Policies logic. To test it add to test project file "policies/isAdmin.go" with similar content:

```
package policies

import (
    "fmt"
    "github.com/astaxie/beego/context"
)

func IsAdmin(ctx *context.Context) {
    fmt.Println("Admin policy")
}
```

Then add comment to any controller or method of controller:

`// @policy IsAdmin`

Thank you,
Oleg Demchenko

### CODE REVIEW

**Comment by astaxie** [comment]
@OlegFX what's the difference with the plugins. all the logic is the same. It's still the same as BeforeExec

**Comment by OlegFX** [comment]
@astaxie currently if you want to add **IsAdmin** policy to a method of controller (for example, "POST"), you should add a BeforeExec filter for path to this controller and manually check HTTP Request Method for all incoming requests inside; if it's a "POST" - you should start IsAdmin logic execution. Another approach is to add one BeforeExec root filter for all policies and search for appropriate controller/method inside.

Both approaches can lead to excessive entanglement code that is critical for big projects.

With the new @policy logic you should just create **IsAdmin** policy and add @policy annotation to corresponding controller methods.

**Comment by astaxie** [comment]
@OlegFX I think policy only append the method to special filter. Maybe we can improve current plugins to support method. what do you think?

**Comment by OlegFX** [comment]
@astaxie Yes, InsertFilter for BeforeRouter with the method is similar to the policy with one "but".

Usually policy - is the list of policies for a method, so we also need to be able to add an arbitrary amount of policies to any method of controller. In addition we need to be able to add policies to the controller (for all methods) and in the case when we have some policy list for controller and for method of this controller - we should check all policies for current method, but skip controller's policies, if found any.

So, policy tree works as logic "OR", choosing just one most appropriate rule. This is different from filters, where we use "AND" logic, executing all appropriate filters.

And another great thing - to be able add @policy annotation to controller or method comments and get all required policy rules in auto-generated .go file.

In my PR all these things implemented.

**Comment by OlegFX** [comment]
@astaxie So, as result - filters are good for common cases. For example, we have own implementation for Sessions. So we can add BeforeRouter filter where we can get user's session with all detailed information, and then we can move to the policies - find one rule for current API method call and check if current user has enough privileges to call this method.

**Comment by astaxie** [comment]
I think it still the same as filter. Just add another router to the logic, that's redundant.

**Comment by euknyaz** [comment]
@astaxie, I see that proposed policies implementation may be useful for better structuring the code and defining policies configuration as annotations. I would agree that it may look redundant counting that it's all just alteration of filters, but with pure filters there will be no separate well-defined layer of policies.

Lets look at SailsJS/nodejs framework policies implementation and documentation at http://sailsjs.org/documentation/concepts/policies
In this doc they stated "When it comes down to it, policies are really just Connect/Express middleware functions which run before your controllers.", so in their case they have extended middleware functions logic (filters in case of beego) and implemented policies on top of it for better structuring of the application. @OlegFX proposing to bind policies  to methods with annotations, which is the key aspect of implementation. This approach looks even better than what SailsJS proposing with policies config file.

Please think of it one more time. It looks like a good idea.

**Comment by smacker** [comment]
looks interesting for me too. Because of imperfection of filters we had to build this layer inside controllers, and it's very wrong.

**Pull request merged**
