### PR TITLE
Retrieve session identifier from cookie and query parameters

### PR DESCRIPTION
**Pull request by yydzero**
Currently beego only retrieve session identifier from cookie in HTTP request.

This pull request try to retrieve session identifier from URL query parameters if could not find from cookie.

Thus following request will works:

CURL -X GET http://example.com/api/resource?gosessionid=

Session identifier is configurable.

### CODE REVIEW

**Comment by astaxie** [comment]
identifier from query is easy. the problem is that we need to return the sessionID to the client if the client not support cookie.

**Comment by yydzero** [comment]
I hope I understand your question correctly. Here is what we are using:

During login request (like http://example.com/api/login?username=<name>&password=<password>, we will return sessionid as part of RESTful response, like:

{
  'status': 'ok',
  'resource': {
        sessionid: <sessionid>
        ....
   }
}

**Comment by astaxie** [comment]
session/session.go:161: undefined: SessionStore
session/session.go:172: manager.sessionId undefined (type *Manager has no field or method sessionId)

**Comment by astaxie** [comment]
I fix it https://github.com/astaxie/beego/commit/ac3a447479046559be0dc34a22b068b5169f8504

**Pull request merged**
