### PR TITLE
go module path compatible when application outside GOPATH

### PR DESCRIPTION
**Pull request by qxhy123**
when application outside GOPATH and set GO111MODULE to "ON" or "AUTO", Annotation router still could generate

### CODE REVIEW

**Comment by wooque** [comment]
https://github.com/astaxie/beego/issues/3450 issue affected by this
@qxhy123 Could you please rebase so this can be merged

**Comment by qxhy123** [comment]
@wooque sure, no problem~

**Comment by qxhy123** [comment]
I plan re-pr to fix this problem, so this pr is closed.

**Comment by pierreneter** [comment]
@qxhy123, please complete it. Thank you.

**Comment by RanQiwu** [comment]
@qxhy123 兄弟什么时候重提啊，都几个月了，我还在等着呢。。。

**Comment by guhan121** [comment]
@qxhy123, please complete it. Thank you.

**Pull request closed without merging**
