### PR TITLE
session.NewManager second params shoube be a object not a string

### PR DESCRIPTION
**Pull request by Maxgis**

### CODE REVIEW

**Comment by astaxie** [comment]
What's the benefit from the Object? If change it will broken the compatibility. If we have a great benefit from this change I will would love to do that. If not I would keep the same API now. What's your opinion?

**Comment by Maxgis** [comment]
用英文解释起来比较费劲

1. 传入string，开发者需要查看相关代码文件，了解config结构，自己手动拼接json。而如果是object，直接就可以通过代码提示，就可以快速的进行设置。这就像提供API一样，隐藏内部细节，向外暴漏参数就可以。


1. 我个人猜测，大部分用户应该还是很少使用sessionConfig这个配置key吧，增删改都十分的不方便，如果遇见需要转义的字符，会跪的。不如使用多个key来配置方便。甚至我觉得都不需要提供这个sessionConfig选项

1. 如果以后更改配置的config的默认值，需要在两个地方更改。如果不提供这个sessionConfig这个配置项，只有一个入口位置，就简单了很多。

1. 之前的方式很奇怪，先把一个object->map->json->object，而我这种方式 就是object->object，就简单了很多

1. managerConfig结构是private，但是里面的属性却是public，这是极其不合理的

**Comment by roxanebellot** [comment]
Indeed the compatibility is broken. Could you explain how are we supposed to use this new version of NewManager ? I can't figure it out :confused: 
(and just a reminder, [the docs](http://beego.me/docs/module/session.md) still recommand the old version)

**Comment by astaxie** [comment]
@roxanebellot how did you use the session manage now? I am really sorry about that broken the compatibility. I will update the docs soon.

**Pull request merged**
