### PR TITLE
refactor color logger

### PR DESCRIPTION
**Pull request by JessonChan**
refactor color logger,easy to read and use

### CODE REVIEW

**Comment by JessonChan** [comment]
Colorful=true(wrong color)
image
Colorful=false(right color)
image

**Comment by JessonChan** [comment]
Maybe we should only color the error level such as [E][I][D] like this
image
not this style
image

**Comment by JessonChan** [comment]
``` javascripte
package main

import (
	"fmt"
	"time"

	logs "github.com/astaxie/beego/logs"
)

func main() {
	logs.SetLogger("console", `{"color":true}`)
	logs.Debug("this is debug")
	logs.Error("this is error")
	fmt.Println("better in color")
	fmt.Println(time.Now().Format("2006/01/02 15:04:05.123 ") + "\033[1;44m" + "[D]" + "\033[0m" + "  this is debug")
	fmt.Println(time.Now().Format("2006/01/02 15:04:05.123 ") + "\033[1;31m" + "[E]" + "\033[0m" + "  this is error")
}
```
image

**Comment by JessonChan** [comment]
windows screen
image
  mac os screen
image

**Comment by hurisheng** [comment]
Why remove the log.go file? With the file removed, original call to log like below is failed which is incompatible with old code.
```
beego.Emergency("this is emergency")
beego.Alert("this is alert")
beego.Critical("this is critical")
beego.Error("this is error")
beego.Warning("this is warning")
beego.Notice("this is notice")
beego.Informational("this is informational")
beego.Debug("this is debug")
```

**Pull request merged**
