### PR TITLE
stmt: fix bug of non concurrent security & add double check

### PR DESCRIPTION
**Pull request by jianzhiyao**

### CODE REVIEW

**Comment by flycash** [comment]
#3791
#3737
#3827

**Comment by szyhf** [comment]
Hi, the main reason of `memory leak` I descripted in #3873 is because the `d.stmts[query]` is set by `query`, but my `query` has really large number of version without params, in different stmt template by '?' as SQL Placeholder, and the `d.stmts` cached them all and never release.

**Comment by flycash** [comment]
> Hi, the main reason of `memory leak` I descripted in #3873 is because the `d.stmts[query]` is set by `query`, but my `query` has really large number of version without params, in different stmt template by '?' as SQL Placeholder, and the `d.stmts` cached them all and never release.
> The lock doesn't case the problem.

#4024

**Comment by flycash** [comment]
we will disable cache in v2.0 by default. #4098

**Pull request merged**
