### PR TITLE
add template asset support

### PR DESCRIPTION
**Pull request by uptoknow**
replace https://github.com/astaxie/beego/pull/2402

### CODE REVIEW

**Comment by uptoknow** [comment]
@astaxie Sorry for the late pr, could you please help review this when you can ?

**Comment by astaxie** [comment]
@uptoknow could you write some documents on how to use it?

**Comment by uptoknow** [comment]
@astaxie Sure, will prepare a pr for the doc repo after this passed review,thanks.

**Comment by uptoknow** [comment]
@astaxie Rebased, please take a look when you can,thanks.

**Comment by sergeylanzman** [comment]
I will update this solutions https://github.com/saturn4er/beego-assets, I think this better

**Comment by astaxie** [comment]
@sergeylanzman this repo looks good

**Comment by sergeylanzman** [comment]
I make fork for my company and improve project. Original project not maintains. Currently i use this i my job. But i have plan for more fetchers.
https://github.com/gtforge/beego-assets

**Comment by astaxie** [comment]
I will close this PR as will use @sergeylanzman beego-assets

**Pull request closed without merging**
