### PR TITLE
add Config.Load func

### PR DESCRIPTION
**Pull request by coseyo**
Add new feature for beego. 

you can load specific config file by run mode, just as below

cf, err := beego.BConfig.Load("auth.json")

It will load conf/dev/auth.json if you run in dev mode, or load conf/prod/auth.json in prod mode.

If can not find the file in above dir, it will load conf/auth.json.

### CODE REVIEW

**Comment by astaxie** [comment]
@coseyo I don't think Load is a correct way to load config for different RunMode. I would to say we need to use include in ini config.

```
[dev]
include "dev.conf"
[prod]
include "prod.conf"
```

**Comment by coseyo** [comment]
@astaxie This method can load different type of adpater file. On the other hand, if the site has many configuration files, it is much clear to put the files in specific path, no need to change the ini config.
well, just in my opinion.

**Comment by astaxie** [comment]
@coseyo I think https://github.com/astaxie/beego/blob/develop/config.go#L315 is what you needed

**Comment by coseyo** [comment]
Maybe there is something different, multi invoking LoadAppConfig func would exec parseConfig multi times, and it would init BConfig multi time. Sometimes, not all config file is used for the app common config.

**Comment by astaxie** [comment]
BConfig only init once. if the config didn't include any variable about BConfig. it still use the old value.

**Comment by coseyo** [comment]
Oh, that's it, My mistake~
For keeping the config file independent, I thnk I would still use the load method for the reason I first mention. support multi adapter and keep the code module's config independent and looks clear.

In fact that I have make a package to do this staff.

https://github.com/coseyo/beeconfig

By the way, is there a github repo to store the third party package for beego ?

**Comment by astaxie** [comment]
@coseyo https://github.com/beego/contrib

**Comment by coseyo** [comment]
good~

**Pull request closed without merging**
