### PR TITLE
demo for support log formatter

### PR DESCRIPTION
**Pull request by flycash**
@IamCathal Please check this.

### CODE REVIEW

**Comment by IamCathal** [comment]
Thank you for this example. I understand the code but I am having trouble even on my own `develop-2.0` branch due to circular dependencies. I am a bit lost in this refactor and I am not sure how to fix these errors as there are a lot of files being moved around. 


Even this simple API is throwing errors:
```go
package main

import (
	"github.com/astaxie/beego"
)

func main() {
	ctrl := &MainController{}
	beego.Router("/yuppa", ctrl, "get:Yuppa")
	beego.Run()
}

type MainController struct {
	beego.Controller
}

func (ctrl *MainController) Yuppa() {
	output := ctrl.Ctx.Output

	output.Header("Content-Type", "application/json")
	ctrl.Ctx.WriteString("working")
}
```
```
cathal@gomei: $ go run main.go
import cycle not allowed
package main
        imports github.com/astaxie/beego
        imports github.com/astaxie/beego/pkg
        imports github.com/astaxie/beego
```

Because of this I can't work on this new logging feature at the moment but I have seen many comments on some functions that could be improved with some better grammar. I'll submit a PR for it and see what you think about it

**Comment by flycash** [comment]
if you change:
```go
import (
	"github.com/astaxie/beego"
)
```

to 
```
import (
	"github.com/astaxie/beego/pkg"
)
```
Does it work?

**Comment by IamCathal** [comment]
Yes this works thank you.

**Comment by IamCathal** [comment]
I've applied your demo code and I'm working to fully implement this feature at the moment :)

**Pull request closed without merging**
