### PR TITLE
Add GroupBy to QuerySeter

### PR DESCRIPTION
**Pull request by pdf**
Adds support for GroupBy to QuerySeter SELECT operations.

### CODE REVIEW

**Comment by astaxie** [comment]
https://drone.io/github.com/astaxie/beego/905 build error

**Comment by pdf** [comment]
@astaxie sorry about that, I think I was having some problems with the postgres setup in my dev environment when I wrote this.  The problem is that postgres doesn't support partial group by, whereas mysql and sqlite do.  As such, some of the tests here do not produce valid queries for postgres, yet the code is behaving as expected.  I'm not sure what the best way to deal with this is, should I conditionally execute those tests only for mysql and sqlite, so that we maintain coverage?  I don't think I can exercise that code in a way that will be valid for every DBMS.

**Comment by y2mao** [comment]
Seter or Setter?

**Comment by pdf** [comment]
@y2mao `QuerySeter`, the struct is `QuerySet`, and the Go convention is to add `er` when creating an interface, hence `QuerySeter`.

**Pull request merged**
