### PR TITLE
Refactor SessionInit method

### PR DESCRIPTION
**Pull request by AllenX2018**
I change the input config string to json and declare provider config struct for every session provider. I think it's enough to just support json as the config string for now. Please review it and if these changes are approved, I will add UT for every provider. @flycash

### CODE REVIEW

**Review by flycash — COMMENTED** [review]
It looks good. 
But I think we should keep compatible with "savePath",  which means that we check the input. If input is in JSON format, we unmarshal it or we go back to old logic. In old logic, we log `Error` (or Warn) to tell users that we only support json format in v2.1.x.

**Comment by AllenX2018** [comment]
> Yes. I think the logs could be the basic module so that it could be used in other modules.

OK. I will add some commit to keep compatible  with the old logic.

> We want to reorganize all modules. So there are many conflicts, don't worry about it. We just move files and do not change the content. It's easy to resolve these conflicts.

No Problem. I will update my fork repo and resolve the conflict myself.

**Comment by flycash** [comment]
> It looks good.
> But I think we should keep compatible with "savePath", which means that we check the input. If input is in JSON format, we unmarshal it or we go back to old logic. In old logic, we log `Error` (or Warn) to tell users that we only support json format in v2.1.x.

@AllenX2018 Just ignore this since we had developed an adapter layer to keep compatible with v1.x. You just need to resolve those conflicts.

**Comment by AllenX2018** [comment]
@flycash ok

**Pull request closed without merging**
