### PR TITLE
fix issue #1597, #1601，#1566

### PR DESCRIPTION
**Pull request by youngsterxyf**
@astaxie Is the change OK？

### CODE REVIEW

**Comment by astaxie** [comment]
@youngsterxyf don't send the PR include so many fixed. one by one will be great.

**Comment by youngsterxyf** [comment]
@astaxie I know, but the pr will append new commits by itself。How can i do？

**Comment by youngsterxyf** [comment]
@astaxie I know what to do now, Thanks。I will use one new branch for one pr

**Comment by astaxie** [comment]
thanks

**Pull request closed without merging**
