### PR TITLE
add field comment on create table

### PR DESCRIPTION
**Pull request by NSObjects**
#3188 建表时通过description标签添加字段注释。

### CODE REVIEW

**Comment by linux-mac** [comment]
我使用 beego 的 1.10.0 版本，但是下面的方式并没有生效？

go 1.10.3
mysql 5.7

```go
	Attribute   string    `orm:"null;description(附属信息)"`
```

**Comment by LiJoah** [comment]
version: ~1.10.1 
Title         string    `orm: "description(文章的标题)" json:"title"` 
没有作用呀 @NSObjects

**Comment by LiJoah** [comment]
@astaxie  
version: ~1.10.1
Title string orm: "description(文章的标题)" json:"title"
没有作用耶

**Comment by NSObjects** [comment]
```
package main

import (
	"github.com/beego"
	"github.com/beego/orm"
	_ "github.com/go-sql-driver/mysql"
)

func init() {
	orm.RegisterDataBase("default", "mysql", "root:123456@tcp(127.0.0.1:3306)/test")
	orm.RegisterModel(new(User))
	orm.RunSyncdb("default", false, true)
}

func main() {
	if beego.BConfig.RunMode == "dev" {
		beego.BConfig.WebConfig.DirectoryIndex = true
		beego.BConfig.WebConfig.StaticDir["/swagger"] = "swagger"
	}
	beego.Run()
}

type User struct {
	Id       int    `orm:"column(id);auto"`
	UserName string `orm:"column(account);size(100)" description:"用户名"`
	Password string `orm:"column(password);size(255)" description:"密码"`
	Username string `orm:"column(username);size(100)" description:"昵称"`
}

```

beego v1.10.1
@LiJoah @linux-mac

**Comment by 19940308cai** [comment]
@NSObjects  
`type User struct{
	Id       int    `orm:"column(id);auto"`
	UserName string `orm:"column(account);size(100)" description:"用户名"`
	Password string `orm:"column(password);size(255)" description:"密码"`
	Username string `orm:"column(username);size(100)" description:"昵称"`
}`

生成之后， show create table user 

`CREATE TABLE `user` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `account` varchar(100) COLLATE utf8_bin NOT NULL DEFAULT '',
  `password` varchar(255) COLLATE utf8_bin NOT NULL DEFAULT '',
  `username` varchar(100) COLLATE utf8_bin NOT NULL DEFAULT '',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin`

**Comment by NSObjects** [comment]
@19940308cai 

版本
```
github.com/astaxie/beego v1.11.1
github.com/go-sql-driver/mysql v1.4.1
google.golang.org/appengine v1.4.0 // indirect
```

```

package main

import (
	"github.com/astaxie/beego"
	"github.com/astaxie/beego/orm"
	_ "github.com/go-sql-driver/mysql"
)

func init() {
	orm.Debug = true
	orm.RegisterDataBase("default", "mysql", "root:123456@tcp(127.0.0.1:3306)/test")
	orm.RegisterModel(new(User))
	orm.RunSyncdb("default", false, true)
}

func main() {
	if beego.BConfig.RunMode == "dev" {
		beego.BConfig.WebConfig.DirectoryIndex = true
		beego.BConfig.WebConfig.StaticDir["/swagger"] = "swagger"
	}

	beego.Run()
}

type User struct {
	Id       int    `orm:"column(id);auto"`
	UserName string `orm:"column(account);size(100)" description:"用户名"`
	Password string `orm:"column(password);size(255)" description:"密码"`
	Username string `orm:"column(username);size(100)" description:"昵称"`
}
```

## log

```
create table `user` 
    -- --------------------------------------------------
    --  Table Structure for `main.User`
    -- --------------------------------------------------
    CREATE TABLE IF NOT EXISTS `user` (
        `id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY,
        `account` varchar(100) NOT NULL DEFAULT ''  COMMENT '用户名',
        `password` varchar(255) NOT NULL DEFAULT ''  COMMENT '密码',
        `username` varchar(100) NOT NULL DEFAULT ''  COMMENT '昵称'
    ) ENGINE=InnoDB;

2019/02/15 09:39:42.123 [I]  http server Running on http://:8080
```

**Comment by Defke** [comment]
上面的这种写法是不对的，正确写法
type User struct {
	Id       int    `orm:"column(id);auto"`
	UserName string `orm:"column(account);size(100);description:(用户名)"`
	Password string `orm:"column(password);size(255);description:(密码)"`
	Username string `orm:"column(username);size(100);description:(昵称)"`
},
我也是看了源码之后才知道的。

**Comment by Defke** [comment]
上面的写法是错误的，正确的写法：
type User struct {
	Id       int    `orm:"column(id);auto"`
	UserName string `orm:"column(account);size(100);description(用户名)`
	Password string `orm:"column(password);size(255);description(密码)`
	Username string `orm:"column(username);size(100);description:(昵称)`
}

**Comment by Defke** [comment]
正确写法:
type User struct {
	Id       int    `orm:"column(id);auto"`
	UserName string `orm:"column(account);size(100);description(用户名)"`
	Password string `orm:"column(password);size(255);description(密码)"`
	Username string `orm:"column(username);size(100);description(昵称)"`
}

**Comment by Defke** [comment]
而且 description括号里不可以有 ";" 跟"(",")"

**Comment by liup1211** [comment]
> 
> 
> 而且 description括号里不可以有 ";" 跟"(",")"

Integral   int64  `orm:"column(integral)"                        description:"积分，也许目前用不到，预留"`
IdNo       string `orm:"column(id_no);size(10);null;description(身份证号)"      

两种方式，我都试了，不行
├── Beego     : 1.9.2
├── GoVersion : go1.14
├── GOOS      : windows
├── GOARCH    : amd64

**Comment by liup1211** [comment]
> 
> 
> @19940308cai
> 
> 版本
> 
> ```
> github.com/astaxie/beego v1.11.1
> github.com/go-sql-driver/mysql v1.4.1
> ```
> 
> ```
> 
> package main
> 
> import (
> 	"github.com/astaxie/beego"
> 	"github.com/astaxie/beego/orm"
> 	_ "github.com/go-sql-driver/mysql"
> )
> 
> func init() {
> 	orm.Debug = true
> 	orm.RegisterDataBase("default", "mysql", "root:123456@tcp(127.0.0.1:3306)/test")
> 	orm.RegisterModel(new(User))
> 	orm.RunSyncdb("default", false, true)
> }
> 
> func main() {
> 	if beego.BConfig.RunMode == "dev" {
> 		beego.BConfig.WebConfig.DirectoryIndex = true
> 		beego.BConfig.WebConfig.StaticDir["/swagger"] = "swagger"
> 	}
> 
> 	beego.Run()
> }
> 
> type User struct {
> 	Id       int    `orm:"column(id);auto"`
> 	UserName string `orm:"column(account);size(100)" description:"用户名"`
> 	Password string `orm:"column(password);size(255)" description:"密码"`
> 	Username string `orm:"column(username);size(100)" description:"昵称"`
> }
> ```
> 
> ## log
> 
> ```
> create table `user` 
>     -- --------------------------------------------------
>     --  Table Structure for `main.User`
>     -- --------------------------------------------------
>     CREATE TABLE IF NOT EXISTS `user` (
>         `id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY,
>         `account` varchar(100) NOT NULL DEFAULT ''  COMMENT '用户名',
>         `password` varchar(255) NOT NULL DEFAULT ''  COMMENT '密码',
>         `username` varchar(100) NOT NULL DEFAULT ''  COMMENT '昵称'
>     ) ENGINE=InnoDB;
> 
> 2019/02/15 09:39:42.123 [I]  http server Running on http://:8080
> ```

Integral   int64  `orm:"column(integral)"                        description:"积分，也许目前用不到，预留"`
IdNo       string `orm:"column(id_no);size(10);null;description(身份证号)"      

两种方式，我都试了，不行
├── Beego     : 1.9.2
├── GoVersion : go1.14
├── GOOS      : windows
├── GOARCH    : amd64

**Comment by liup1211** [comment]
> 
> 
> @19940308cai
> 
> 版本
> 
> ```
> github.com/astaxie/beego v1.11.1
> github.com/go-sql-driver/mysql v1.4.1
> ```
> 
> ```
> 
> package main
> 
> import (
> 	"github.com/astaxie/beego"
> 	"github.com/astaxie/beego/orm"
> 	_ "github.com/go-sql-driver/mysql"
> )
> 
> func init() {
> 	orm.Debug = true
> 	orm.RegisterDataBase("default", "mysql", "root:123456@tcp(127.0.0.1:3306)/test")
> 	orm.RegisterModel(new(User))
> 	orm.RunSyncdb("default", false, true)
> }
> 
> func main() {
> 	if beego.BConfig.RunMode == "dev" {
> 		beego.BConfig.WebConfig.DirectoryIndex = true
> 		beego.BConfig.WebConfig.StaticDir["/swagger"] = "swagger"
> 	}
> 
> 	beego.Run()
> }
> 
> type User struct {
> 	Id       int    `orm:"column(id);auto"`
> 	UserName string `orm:"column(account);size(100)" description:"用户名"`
> 	Password string `orm:"column(password);size(255)" description:"密码"`
> 	Username string `orm:"column(username);size(100)" description:"昵称"`
> }
> ```
> 
> ## log
> 
> ```
> create table `user` 
>     -- --------------------------------------------------
>     --  Table Structure for `main.User`
>     -- --------------------------------------------------
>     CREATE TABLE IF NOT EXISTS `user` (
>         `id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY,
>         `account` varchar(100) NOT NULL DEFAULT ''  COMMENT '用户名',
>         `password` varchar(255) NOT NULL DEFAULT ''  COMMENT '密码',
>         `username` varchar(100) NOT NULL DEFAULT ''  COMMENT '昵称'
>     ) ENGINE=InnoDB;
> 
> 2019/02/15 09:39:42.123 [I]  http server Running on http://:8080
> ```

Integral   int64  `orm:"column(integral)"                        description:"积分，也许目前用不到，预留"`
IdNo       string `orm:"column(id_no);size(10);null;description(身份证号)"      

两种方式，我都试了，不行
├── Beego     : 1.9.2
├── GoVersion : go1.14
├── GOOS      : windows
├── GOARCH    : amd64

**Pull request merged**
