### PR TITLE
Start timer task Multiple times

### PR DESCRIPTION
**Pull request by albertma**
I found an issue for create multiple goroutines to handle the timer task list.

### CODE REVIEW

**Comment by astaxie** [comment]
@albertma please send the PR to develop branch.

**Comment by albertma** [comment]
do you mean file the bug on issue tracking system?

**Comment by astaxie** [comment]
no, now you send the PR to  astaxie:master from albertma:master. it should be astaxie:develop from albertma:master

**Comment by albertma** [comment]
I see

**Pull request closed without merging**
