### PR TITLE
add JsonBody

### PR DESCRIPTION
**Pull request by fugr**
easy to new a request with body encoding by JSON.

### CODE REVIEW

**Comment by mattn** [comment]
please merge this into master because [bat](https://github.com/astaxie/bat) is not possible to build.

**Comment by astaxie** [comment]
@mattn it's already merger into beego's develop branch. because bat is still in process, if you want to try you can get into the beego, and `git checkout develop` then you can build bat.

**Comment by mattn** [comment]
okay, but i love `go get`. :)

**Comment by astaxie** [comment]
yea, I will release beego ASAP. Now it's still in develop. because I want to add proxy and auth into bat. So maybe still need to change the httplib.

**Comment by astaxie** [comment]
@mattn I just remove the beego dependence. move httplib to the bat. When it stable can move to beego

**Comment by mattn** [comment]
thanks

**Pull request merged**
