### PR TITLE
Add RouterPattern to context.Input

### PR DESCRIPTION
**Pull request by smacker**
Right now beego adds this param only in dev mode, but I noticed that it's very useful to have in prod environment to.
My current use case - filter that sends logs in newrelic. Pattern there will help a lot to generate correct transaction name.

### CODE REVIEW

**Comment by smacker** [comment]
actually I realized it's impossible to build general solution without RouterPattern :(

**Comment by sergeylanzman** [comment]
I writer solution for newrelic and beego,  yes router pattern this good case.  @smacker  check my solution

**Comment by smacker** [comment]
@sergeylanzman it doesn't work for us. Because we use UUID instead of integer ids. Of course I made a work around for our specific case, but it won't work in general case. Consider url pattern:
```
/api/entity/:uuid/products/:type(any string)
```

You can't replace `someWeirdStringFromDatabase` to `:type`. (okay, you can with a complicated logic based on `ctx.Input.Params()`, but better don't do like that)

**Comment by sergeylanzman** [comment]
You are right, and this PR fixed this problem

**Pull request merged**
