### PR TITLE
orm insertorupdate

### PR DESCRIPTION
**Pull request by fudali113**
http://blog.csdn.net/fudali133/article/details/51913802

### CODE REVIEW

**Comment by astaxie** [comment]
@fudali113 could you add test case

**Comment by fudali113** [comment]
@astaxie  Yes, I can.But need some time

**Comment by astaxie** [comment]
@fudali113 cool. Take your time

**Comment by fudali113** [comment]
@astaxie 

# sql:


CREATE TABLE public.pgsql_test
(
    id SERIAL PRIMARY KEY,
    unique1 CHARACTER(30),
    other1 INT,
    other2 CHARACTER(30)
);
CREATE UNIQUE INDEX pgsql_test_unique1_uindex ON public.pgsql_test (unique1);

CREATE TABLE monitor.mysql_test
(
    id INT PRIMARY KEY AUTO_INCREMENT,
    unique1 CHARACTER(30),
    other1 INT,
    other2 CHARACTER(30)
);
CREATE UNIQUE INDEX mysql_test_unique1_uindex ON monitor.mysql_test # (unique1);

# code:


`package main

import (
	"fmt"
	"strings"
	"time"

	"github.com/astaxie/beego/orm"
	_ "github.com/go-sql-driver/mysql"
	_ "github.com/lib/pq"
)

type Test1 struct {
	Id      int64
	Unique1 string
	Other1  int64
	Other2  string
}

func (a *Test1) TableName() string {
	return "mysql_test"
}

type Test2 struct {
	Id      int64
	Unique1 string
	Other1  int64
	Other2  string
}

func (a *Test2) TableName() string {
	return "pgsql_test"
}

func init() {
	orm.RegisterModel(new(Test1), new(Test2))
	orm.RegisterDriver("mysql", orm.DRMySQL)
	orm.RegisterDataBase("default", "mysql", "root:Tt7896357@(120.26.235.113:6666)/monitor?charset=utf8")
	orm.RegisterDriver("postgres", orm.DRPostgres)
	orm.RegisterDataBase("pgsql", "postgres", "user=postgres password=Tt7896357 dbname=postgres sslmode=disable")
	orm.Debug = true
}

var (
	testModel   = Test1{Unique1: "u", Other1: 1, Other2: "o"}
	testModel1  = Test1{Unique1: "u", Other1: 2, Other2: "o"}
	testModel2  = Test1{Unique1: "u", Other1: 3, Other2: "oo"}
	_testModel  = Test2{Unique1: "u", Other1: 1, Other2: "o"}
	_testModel1 = Test2{Unique1: "u", Other1: 2, Other2: "o"}
	_testModel2 = Test2{Unique1: "u", Other1: 3, Other2: "oo"}
)

func testMysqlInsertOrUpdate() {
	db := orm.NewOrm()
	db.Using("mysql")
	db.Insert(&testModel)
	//test1  普通操作
	db.InsertOrUpdate(&testModel1)
	test1 := Test1{Unique1: "u"}
	time.Sleep(time.Second * 1)
	db.Read(&test1, "Unique1")
	fmt.Print(test1)
	fmt.Print("       test1 --->        ")
	fmt.Println(testModel1.Other1 == test1.Other1)
	//test2  普通操作
	db.InsertOrUpdate(&testModel2)
	time.Sleep(time.Second * 1)
	db.Read(&test1, "Unique1")
	fmt.Print(test1)
	fmt.Print("       test2 --->        ")
	fmt.Println(testModel2.Other1 == test1.Other1 && testModel2.Other2 == test1.Other2)
	//test3  字符串与数字 + 操作
	db.InsertOrUpdate(&testModel2, "other1=other1+1", "other2=concat(other2,'o')")
	time.Sleep(time.Second * 1)
	db.Read(&test1, "Unique1")
	fmt.Print(test1)
	fmt.Print("       test3 --->        ")
	fmt.Println(testModel2.Other1+1 == test1.Other1 && testModel2.Other2+"o" == test1.Other2)
	//test4 数字 - 操作
	db.InsertOrUpdate(&testModel2, "other1=other1-1")
	time.Sleep(time.Second * 1)
	db.Read(&test1, "Unique1")
	fmt.Print(test1)
	fmt.Print("       test4 --->        ")
	fmt.Println((testModel2.Other1+1)-1 == test1.Other1)
	//test5  数字 * 操作
	db.InsertOrUpdate(&testModel2, "other1=other1*3")
	time.Sleep(time.Second * 1)
	db.Read(&test1, "Unique1")
	fmt.Print(test1)
	fmt.Print("       test5 --->        ")
	fmt.Println(((testModel2.Other1+1)-1)*3 == test1.Other1)
	//test6  数字 / 操作
	db.InsertOrUpdate(&testModel2, "other1=other1/3")
	time.Sleep(time.Second * 1)
	db.Read(&test1, "Unique1")
	fmt.Print(test1)
	fmt.Print("       test6 --->        ")
	fmt.Println((((testModel2.Other1+1)-1)*3)/3 == test1.Other1)
}

func testPgsqlInsertOrUpdate() {
	db := orm.NewOrm()
	db.Using("pgsql")
	db.Insert(&_testModel)
	//test1  普通操作
	db.InsertOrUpdate(&_testModel1, "unique1")
	test1 := Test2{Unique1: "u"}
	time.Sleep(time.Second * 1)
	db.Read(&test1, "Unique1")
	fmt.Print(test1)
	fmt.Print("       test1 --->        ")
	fmt.Println(testModel1.Other1 == test1.Other1)
	//test2  普通操作
	db.InsertOrUpdate(&_testModel2, "unique1")
	time.Sleep(time.Second * 1)
	db.Read(&test1, "Unique1")
	fmt.Print(test1)
	fmt.Print("       test2 --->        ")
	fmt.Println(testModel2.Other1 == test1.Other1 && testModel2.Other2 == strings.TrimSpace(test1.Other2))
	//test3  字符串与数字 + 操作
	db.InsertOrUpdate(&_testModel2, "unique1", "other1=other1+1", "other2=other2 || 'o'")
	time.Sleep(time.Second * 1)
	db.Read(&test1, "Unique1")
	fmt.Print(test1)
	fmt.Print("       test3 --->        ")
	fmt.Println(testModel2.Other1+1 == test1.Other1 && testModel2.Other2+"o" == strings.TrimSpace(test1.Other2))
	//test4 数字 - 操作
	db.InsertOrUpdate(&_testModel2, "unique1", "other1=other1-1")
	time.Sleep(time.Second * 1)
	db.Read(&test1, "Unique1")
	fmt.Print(test1)
	fmt.Print("       test4 --->        ")
	fmt.Println((testModel2.Other1+1)-1 == test1.Other1)
	//test5  数字 * 操作
	db.InsertOrUpdate(&_testModel2, "unique1", "other1=other1*3")
	time.Sleep(time.Second * 1)
	db.Read(&test1, "Unique1")
	fmt.Print(test1)
	fmt.Print("       test5 --->        ")
	fmt.Println(((testModel2.Other1+1)-1)*3 == test1.Other1)
	//test6  数字 / 操作
	_, err := db.InsertOrUpdate(&_testModel2, "unique1", "other1=other1/3")
	if err != nil {
		fmt.Println(err)
	}
	time.Sleep(time.Second * 1)
	db.Read(&test1, "Unique1")
	fmt.Print(test1)
	fmt.Print("       test6 --->        ")
	fmt.Println((((testModel2.Other1+1)-1)*3)/3 == test1.Other1)
}

func main() {
	testMysqlInsertOrUpdate()
	testPgsqlInsertOrUpdate()
}
`


# result:

[ORM] - 2016-07-16 18:32:04 - [Queries/default] - [  OK /     db.Exec /   132.1ms] - [INSERT INTO `mysql_test` (`unique1`, `other1`, `other2`) VALUES (?, ?, ?)] - `u`, `1`, `o`
[ORM] - 2016-07-16 18:32:05 - [Queries/default] - [  OK /     db.Exec /   102.3ms] - [INSERT INTO `mysql_test` (`unique1`, `other1`, `other2`) VALUES (?, ?, ?) ON DUPLICATE KEY UPDATE unique1=?, other1=?, other2=?] - `u`, `2`, `o`, `u`, `2`, `o`
[ORM] - 2016-07-16 18:32:06 - [Queries/default] - [  OK / db.QueryRow /    94.5ms] - [SELECT `id`, `unique1`, `other1`, `other2` FROM `mysql_test` WHERE `unique1` = ?] - `u`
{1 u 2 o}       test1 --->        true
[ORM] - 2016-07-16 18:32:06 - [Queries/default] - [  OK /     db.Exec /   103.0ms] - [INSERT INTO `mysql_test` (`unique1`, `other1`, `other2`) VALUES (?, ?, ?) ON DUPLICATE KEY UPDATE unique1=?, other1=?, other2=?] - `u`, `3`, `oo`, `u`, `3`, `oo`
[ORM] - 2016-07-16 18:32:07 - [Queries/default] - [  OK / db.QueryRow /    94.1ms] - [SELECT `id`, `unique1`, `other1`, `other2` FROM `mysql_test` WHERE `unique1` = ?] - `u`
{1 u 3 oo}       test2 --->        true
[ORM] - 2016-07-16 18:32:07 - [Queries/default] - [  OK /     db.Exec /   119.5ms] - [INSERT INTO `mysql_test` (`unique1`, `other1`, `other2`) VALUES (?, ?, ?) ON DUPLICATE KEY UPDATE unique1=?, other1=other1+1, other2=concat(other2,'o')] - `u`, `3`, `oo`, `u`
[ORM] - 2016-07-16 18:32:08 - [Queries/default] - [  OK / db.QueryRow /    95.8ms] - [SELECT `id`, `unique1`, `other1`, `other2` FROM `mysql_test` WHERE `unique1` = ?] - `u`
{1 u 4 ooo}       test3 --->        true
[ORM] - 2016-07-16 18:32:08 - [Queries/default] - [  OK /     db.Exec /   106.3ms] - [INSERT INTO `mysql_test` (`unique1`, `other1`, `other2`) VALUES (?, ?, ?) ON DUPLICATE KEY UPDATE unique1=?, other1=other1-1, other2=?] - `u`, `3`, `oo`, `u`, `oo`
[ORM] - 2016-07-16 18:32:09 - [Queries/default] - [  OK / db.QueryRow /   101.3ms] - [SELECT `id`, `unique1`, `other1`, `other2` FROM `mysql_test` WHERE `unique1` = ?] - `u`
{1 u 3 oo}       test4 --->        true
[ORM] - 2016-07-16 18:32:09 - [Queries/default] - [  OK /     db.Exec /   161.9ms] - [INSERT INTO `mysql_test` (`unique1`, `other1`, `other2`) VALUES (?, ?, ?) ON DUPLICATE KEY UPDATE unique1=?, other1=other1*3, other2=?] - `u`, `3`, `oo`, `u`, `oo`
[ORM] - 2016-07-16 18:32:11 - [Queries/default] - [  OK / db.QueryRow /   146.8ms] - [SELECT `id`, `unique1`, `other1`, `other2` FROM `mysql_test` WHERE `unique1` = ?] - `u`
{1 u 9 oo}       test5 --->        true
[ORM] - 2016-07-16 18:32:11 - [Queries/default] - [  OK /     db.Exec /   165.3ms] - [INSERT INTO `mysql_test` (`unique1`, `other1`, `other2`) VALUES (?, ?, ?) ON DUPLICATE KEY UPDATE unique1=?, other1=other1/3, other2=?] - `u`, `3`, `oo`, `u`, `oo`
[ORM] - 2016-07-16 18:32:12 - [Queries/default] - [  OK / db.QueryRow /   140.7ms] - [SELECT `id`, `unique1`, `other1`, `other2` FROM `mysql_test` WHERE `unique1` = ?] - `u`
{1 u 3 oo}       test6 --->        true
[ORM] - 2016-07-16 18:32:12 - [Queries/pgsql] - [  OK / db.QueryRow /     4.6ms] - [INSERT INTO "pgsql_test" ("unique1", "other1", "other2") VALUES ($1, $2, $3) RETURNING "id"] - `u`, `1`, `o`
[ORM] - 2016-07-16 18:32:12 - [Queries/pgsql] - [  OK / db.QueryRow /     1.9ms] - [INSERT INTO "pgsql_test" ("unique1", "other1", "other2") VALUES ($1, $2, $3) ON CONFLICT (unique1) DO UPDATE SET unique1=$4, other1=$5, other2=$6 RETURNING "id"] - `u`, `2`, `o`, `u`, `2`, `o`
[ORM] - 2016-07-16 18:32:13 - [Queries/pgsql] - [  OK / db.QueryRow /     2.5ms] - [SELECT "id", "unique1", "other1", "other2" FROM "pgsql_test" WHERE "unique1" = $1] - `u`
{1 u                              2 o                             }       test1 --->        true
[ORM] - 2016-07-16 18:32:13 - [Queries/pgsql] - [  OK / db.QueryRow /     3.3ms] - [INSERT INTO "pgsql_test" ("unique1", "other1", "other2") VALUES ($1, $2, $3) ON CONFLICT (unique1) DO UPDATE SET unique1=$4, other1=$5, other2=$6 RETURNING "id"] - `u`, `3`, `oo`, `u`, `3`, `oo`
[ORM] - 2016-07-16 18:32:14 - [Queries/pgsql] - [  OK / db.QueryRow /     1.8ms] - [SELECT "id", "unique1", "other1", "other2" FROM "pgsql_test" WHERE "unique1" = $1] - `u                             `
{1 u                              3 oo                            }       test2 --->        true
[ORM] - 2016-07-16 18:32:14 - [Queries/pgsql] - [  OK / db.QueryRow /     4.0ms] - [INSERT INTO "pgsql_test" ("unique1", "other1", "other2") VALUES ($1, $2, $3) ON CONFLICT (unique1) DO UPDATE SET unique1=$4, other1=(select other1+1 from pgsql_test where unique1 = $5 ), other2=(select other2 || 'o' from pgsql_test where unique1 = $6 ) RETURNING "id"] - `u`, `3`, `oo`, `u`, `u`, `u`
[ORM] - 2016-07-16 18:32:15 - [Queries/pgsql] - [  OK / db.QueryRow /     2.1ms] - [SELECT "id", "unique1", "other1", "other2" FROM "pgsql_test" WHERE "unique1" = $1] - `u                             `
{1 u                              4 ooo                           }       test3 --->        true
[ORM] - 2016-07-16 18:32:15 - [Queries/pgsql] - [  OK / db.QueryRow /     3.4ms] - [INSERT INTO "pgsql_test" ("unique1", "other1", "other2") VALUES ($1, $2, $3) ON CONFLICT (unique1) DO UPDATE SET unique1=$4, other1=(select other1-1 from pgsql_test where unique1 = $5 ), other2=$6 RETURNING "id"] - `u`, `3`, `oo`, `u`, `u`, `oo`
[ORM] - 2016-07-16 18:32:16 - [Queries/pgsql] - [  OK / db.QueryRow /     2.4ms] - [SELECT "id", "unique1", "other1", "other2" FROM "pgsql_test" WHERE "unique1" = $1] - `u                             `
{1 u                              3 oo                            }       test4 --->        true
[ORM] - 2016-07-16 18:32:16 - [Queries/pgsql] - [  OK / db.QueryRow /     3.4ms] - [INSERT INTO "pgsql_test" ("unique1", "other1", "other2") VALUES ($1, $2, $3) ON CONFLICT (unique1) DO UPDATE SET unique1=$4, other1=(select other1*3 from pgsql_test where unique1 = $5 ), other2=$6 RETURNING "id"] - `u`, `3`, `oo`, `u`, `u`, `oo`
[ORM] - 2016-07-16 18:32:17 - [Queries/pgsql] - [  OK / db.QueryRow /     2.0ms] - [SELECT "id", "unique1", "other1", "other2" FROM "pgsql_test" WHERE "unique1" = $1] - `u                             `
{1 u                              9 oo                            }       test5 --->        true
[ORM] - 2016-07-16 18:32:17 - [Queries/pgsql] - [  OK / db.QueryRow /     4.9ms] - [INSERT INTO "pgsql_test" ("unique1", "other1", "other2") VALUES ($1, $2, $3) ON CONFLICT (unique1) DO UPDATE SET unique1=$4, other1=(select other1/3 from pgsql_test where unique1 = $5 ), other2=$6 RETURNING "id"] - `u`, `3`, `oo`, `u`, `u`, `oo`
[ORM] - 2016-07-16 18:32:18 - [Queries/pgsql] - [  OK / db.QueryRow /     2.0ms] - [SELECT "id", "unique1", "other1", "other2" FROM "pgsql_test" WHERE "unique1" = $1] - `u                             `
{1 u                              3 oo                            }       test6 --->        true

**Comment by astaxie** [comment]
@fudali113 please update the test case inside the ORM.

**Comment by fudali113** [comment]
不好意思，我英语不怎么好而且这是我第一次参与开源项目。
可能有点没理解到你的意思，接下来我会抽时间把单元测试写入orm_test.go，是这样吗？
因为我自身知识的缺乏给您带来一定的不便我深表歉意

**Comment by astaxie** [comment]
@fudali113 恩，你的理解正确了，😄，谢谢奉献你的第一次给beego, 👍

**Comment by fudali113** [comment]
@astaxie 恩，好的😃！我会尽快抽时间完成并提交的。

**Comment by doobfy** [comment]
@astaxie 
测试写好了，但是怎么都没能通过测试。
mysql我的测试方法通过了但是其他好像有一些方法没有通过，
postgres应该是测试postgres版本为9.4，但我利用的是9.5及之后版本postgres的特性，所以导致测试失败

**Comment by astaxie** [comment]
make sure all the test case is passed

**Pull request closed without merging**
