### PR TITLE
fix issue #4311

### PR DESCRIPTION
**Pull request by AllenX2018**
fix issue #4311 

Modify return of `Cache.GetMulti` using "try-best" logic

### CODE REVIEW

**Comment by jianzhiyao** [comment]
All files checked, but you should CI testing passed

**Review by jianzhiyao — COMMENTED** [review]
All files checked, but you should CI testing passed

**Comment by AllenX2018** [comment]
> All files checked, but you should CI testing passed

This is the CI error log (https://travis-ci.org/github/astaxie/beego/jobs/744324821)
```
There was an error in the .travis.yml file from which we could not recover.
Unfortunately, we do not know much about this error.
Please review https://docs.travis-ci.com, or contact us at support@travis-ci.com with the error ID: ee5ad10c958d4c3c80f2d163d911131f
```
It seems that the CI problem isn't caused by code modifications.
Could you please help me re-trigger the CI? I don't have access.
Thanks.

**Comment by jianzhiyao** [comment]
> > All files checked, but you should CI testing passed
> 
> This is the CI error log (https://travis-ci.org/github/astaxie/beego/jobs/744324821)
> 
> ```
> There was an error in the .travis.yml file from which we could not recover.
> Unfortunately, we do not know much about this error.
> Please review https://docs.travis-ci.com, or contact us at support@travis-ci.com with the error ID: ee5ad10c958d4c3c80f2d163d911131f
> ```
> 
> It seems that the CI problem isn't caused by code modifications.
> Could you please help me re-trigger the CI? I don't have access.
> Thanks.

Just restart it

**Comment by AllenX2018** [comment]
> Just restart it

I can see the "restart buid" button in my own repositories, but I can't see the it in "astaxie/beego"，maybe because I have no access.  So please help me restart it. Thanks.

**Comment by AllenX2018** [comment]
@jianzhiyao The CI testing has been restarted and passed now.

**Review by jianzhiyao — APPROVED** [review]

**Pull request merged**
